services:
  app:
    image: arm64v8/amazoncorretto:17-alpine-jdk
    volumes:
      - ./src:/app/src
      - ./gradle:/app/gradle
      - ./build.gradle:/app/build.gradle
      - ./gradlew:/app/gradlew
      - ./gradlew.bat:/app/gradlew.bat
      - ./settings.gradle:/app/settings.gradle
    working_dir: /app
    ports:
      - 8080:8080
    command: [ "./gradlew", "bootrun" ]
    restart: always